obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: 0.105

inflation_radius:  2 
cost_scaling_factor: 5

map_type: costmap
observation_sources: scan
scan: {sensor_frame: /tb3_0/base_scan, data_type: LaserScan, topic: tb3_0/scan, marking: true, clearing: true, max_obstacle_height: 3, 
    min_obstacle_height: -2}
