
shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
# http://wiki.ros.org/nav_core#BaseGlobalPlanner
base_global_planner: "navfn/NavfnROS"

# local planner
# The name of the plugin for the local planner to use with move_base.
# This plugin must adhere to the nav_core::BaseLocalPlanner interface
# specified in the nav_core package.
#
# http://wiki.ros.org/nav_core#BaseLocalPlanner
base_local_planner: "dwa_local_planner/DWAPlannerROS"
 
