local_costmap:
  observation_sources: scan
  scan: {
    sensor_frame: tb3_1/base_scan,
    topic: /tb3_1/scan,
    data_type: LaserScan, 
    expected_update_rate: 0.4,
    observation_persistence: 0.0, 
    marking: true, 
    clearing: true, 
    max_obstacle_height: 2, 
    min_obstacle_height: -1,
    }
  global_frame: tb3_1/map
  robot_base_frame: tb3_1/base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 1

  static_map: false  
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  
